name: update
on: push

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: 'W8c5l5HwhgPgi9UVcUPFB6jtn-1W8H1UkwVsZOoG'

      - name: Find npm cache
        id: npm-cache-path
        run: echo "::set-output name=dir::$(npm cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/npm.lock') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --immutable

      - name: Publish update
        run: eas update --auto